Default: &defaults
  database: golbi.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: golbi_test.sqlite3
  <<: *defaults

Staging:
  database: golbi_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: golbi_production.sqlite3
  poolsize: 100
  <<: *defaults
